# Generated by Django 5.0.6 on 2024-06-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('alt_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('country', models.CharField(choices=[('NG', 'Nigeria')], max_length=2)),
                ('city', models.CharField(choices=[('LA', 'Lagos'), ('IB', 'Ibadan')], max_length=2)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Supplier',
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'Dollars')], max_length=3)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
            },
        ),
    ]
