# Generated by Django 5.0.6 on 2024-06-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira')], max_length=3),
        ),
    ]
