# Generated by Django 5.0.6 on 2024-06-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_price_inventory_unit_price_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira')], default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(choices=[('NG', 'Nigeria')], default='NG', max_length=2),
        ),
    ]
