# Generated by Django 5.0.6 on 2024-06-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_currency_alter_supplier_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='supplier',
            new_name='supplier_id',
        ),
    ]
