# Generated by Django 5.0.6 on 2024-06-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_supplier_inventory_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
